### PR TITLE
Adding my book details

### PR DESCRIPTION
**Pull request by kjmears**
Some lovely people made this site, giving me the opportunity to revive
my little book

### CODE REVIEW

**Comment by kjmears** [comment]
Apologies for the multiple PRs - Forking a repo with gh-pages always catches me out. All my repos then publish under my domain.

**Comment by andydavies** [comment]
@kjmears There's no book-url in sketchnoting.md, was that your intention?

**Comment by kjmears** [comment]
Yeah - I haven't decided what to do yet.

**Comment by andydavies** [comment]
@kjmears I don't know the templating well enough to know what happens when the book url is missing but to me it looks like it'll break? 

@maban Can you confirm?

**Pull request closed without merging**
